feat: add error logging, refactor some functions
knihobot/nextjs-typed-router pull request #16
Opened 2024-03-14 14:00 UTC by vladakopejsek

2024-03-22 09:09 UTC, jancama2 requested changes

2024-03-22 09:09 UTC, jancama2 commented on src/enhancement-functions/matchRealAddressByRouteName.ts
>    locale?: Locales,
To locale by mělo být IMHO povinné.

2024-03-22 09:09 UTC, jancama2 commented on src/enhancement-functions/matchRealAddressByRouteName.ts
> +      throw new Error(
```ts
class ValidationError extends Error {
  constructor(type: routeName: string, locale: string) {
    super(`No route with provided key ${routeName} exists in routes object for locale ${locale}`);
  }
}

throw new ValidationError(routeName, locale)
```

2024-03-22 09:09 UTC, jancama2 commented on src/enhancement-functions/matchRealAddressByRouteName.spec.ts
> +      ),
```suggestion
      new ValidationError("no-fallback", "fr")
```

2024-03-22 09:11 UTC, jancama2 commented
Udělal bych ty custom errory, používal je všude a vyexportoval z balíčku, aby se pak dalo testovat
```ts
try {
   // použití funkce z typed routeru
}
catch (e) {
   if (e instanceof @knihobotRouter.ValidationError) {
      // nějaká logika
   }
}
```

2024-04-09 08:32 UTC, pohy commented on src/enhancement-functions/matchRealAddressByRouteName.ts
> +      throw new Error(
A `type`, `routename` a `locale` by mohly být public fieldy:
```typescript
...
constructor(public type: NejakyTyp, public routeName: string, public locale: string) {
...
```

2024-04-10 10:55 UTC, merged